apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fundval
  namespace: fundval
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: fundval.example.com  # 改成你的域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fundval
                port:
                  number: 21345
